### ISSUE TITLE
URL file command

### ISSUE THREAD

**Issue by rayegleekel** [mikeizbicki/metahtml#28]
I have already confirmed the URLs exist (I removed the ones that didn't from my url/week1-raye file) and have previously been successful when I run the command:
```
cat urls/week1-raye | xargs python3 tests/test_golden.py --insert_urls
```
But now when I ran that command I got this output: 
```
WARNING: url= http://autonewsproo.blogspot.com/2017/11/fact-us-military-considered-using_18.html already added; overwriting
WARNING: url= http://beijingcream.com/2012/12/pyongyang-racer-how-fast-can-you-speed-around-north-koreas-capital-city/ already added; overwriting
WARNING: url= http://blog.keia.org/2013/04/why-north-korea-isnt-interested-in-economic-reform/ already added; overwriting
WARNING: url= http://blogs.reuters.com/fullfocus/2011/10/06/hungry-in-north-korea/ already added; overwriting
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dateutil/parser/_parser.py:1218: UnknownTimezoneWarning: tzname KST identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.
  category=UnknownTimezoneWarning)
downloading url= /Economy/North-Korea-finds-a-new-friend-in-Russia ... WARNING: no html found for url= /Economy/North-Korea-finds-a-new-friend-in-Russia
downloading url= / ... WARNING: no html found for url= /
downloading url= / ... WARNING: no html found for url= /
downloading url= / ... WARNING: no html found for url= /
downloading url= / ... WARNING: no html found for url= /
Rayes-MBP:metahtml rayegleekel$ cat urls/week1-raye | xargs python3 tests/test_golden.py --insert_urls
WARNING: url= http://autonewsproo.blogspot.com/2017/11/fact-us-military-considered-using_18.html already added; overwriting
WARNING: url= http://beijingcream.com/2012/12/pyongyang-racer-how-fast-can-you-speed-around-north-koreas-capital-city/ already added; overwriting
WARNING: url= http://blog.keia.org/2013/04/why-north-korea-isnt-interested-in-economic-reform/ already added; overwriting
WARNING: url= http://blogs.reuters.com/fullfocus/2011/10/06/hungry-in-north-korea/ already added; overwriting
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dateutil/parser/_parser.py:1218: UnknownTimezoneWarning: tzname KST identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.
  category=UnknownTimezoneWarning)
downloading url= /Economy/North-Korea-finds-a-new-friend-in-Russia ... WARNING: no html found for url= /Economy/North-Korea-finds-a-new-friend-in-Russia
downloading url= / ... WARNING: no html found for url= /
downloading url= / ... WARNING: no html found for url= /
downloading url= / ... WARNING: no html found for url= /
downloading url= / ... WARNING: no html found for url= /
```
Also, I noticed that running this command each time adds different entries to the golden.csv files; so each time I run the command it is pulling different articles/related articles. Any idea what is going on? 

Thanks!

**Comment by mikeizbicki** [comment]
These lines:
```
downloading url= /Economy/North-Korea-finds-a-new-friend-in-Russia ... WARNING: no html found for url= /Economy/North-Korea-finds-a-new-friend-in-Russia
downloading url= / ... WARNING: no html found for url= /
downloading url= / ... WARNING: no html found for url= /
downloading url= / ... WARNING: no html found for url= /
downloading url= / ... WARNING: no html found for url= /
```
make me think there's a bug in how my code interacts with the html files that you have.  Can you narrow down which of the urls is causing these lines to be output?

If I know which url, I'll be able to look at it in detail and fix it.  Also, you can skip that url until I get it fixed.

**Comment by rayegleekel** [comment]
I removed the following URL from urls/week1-raye that appeared to initiate the problem: 
http://asia.nikkei.com/magazine/20140710-Latin-America-Asia-Emerging-routes/Politics-Economy/North-Korea-finds-a-new-friend-in-Russia. 
After doing this and running the 
```
$cat urls/week1-raye | xargs python3 tests/test_golden.py --insert_urls
```
I got the following output: 
```
WARNING: url= http://autonewsproo.blogspot.com/2017/11/fact-us-military-considered-using_18.html already added; overwriting
WARNING: url= http://beijingcream.com/2012/12/pyongyang-racer-how-fast-can-you-speed-around-north-koreas-capital-city/ already added; overwriting
WARNING: url= http://blog.keia.org/2013/04/why-north-korea-isnt-interested-in-economic-reform/ already added; overwriting
WARNING: url= http://blogs.reuters.com/fullfocus/2011/10/06/hungry-in-north-korea/ already added; overwriting
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dateutil/parser/_parser.py:1218: UnknownTimezoneWarning: tzname KST identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.
  category=UnknownTimezoneWarning)
```
It appears to have stopped running through the URLs after the reuters.com host URL. I have meetings on and off today for my other job but will try to log onto zoom this afternoon.

**Comment by mikeizbicki** [comment]
This should be fixed in the latest commit.

**Comment by rayegleekel** [comment]
Is the command
```
$git pull upstream master
```
what I want to use to update my repo to the latest commit?

**Comment by rayegleekel** [comment]
I ran the commands:
```
$git remote add upstream https://github.com/mikeizbicki/metahtml.git
$git pull upstream master
```
and got the output: 
```
remote: Enumerating objects: 889, done.
remote: Counting objects: 100% (889/889), done.
remote: Compressing objects: 100% (492/492), done.
remote: Total 1094 (delta 175), reused 886 (delta 172), pack-reused 205
Receiving objects: 100% (1094/1094), 13.61 MiB | 7.95 MiB/s, done.
Resolving deltas: 100% (246/246), completed with 13 local objects.
From https://github.com/mikeizbicki/metahtml
 * branch            master     -> FETCH_HEAD
 * [new branch]      master     -> upstream/master
Updating 0352185..63cd6f5
error: Your local changes to the following files would be overwritten by merge:
	metahtml/timestamp.py
	tests/.cache/invalid
	tests/golden.csv
Please commit your changes or stash them before you merge.
Aborting
```
I don't think it worked as when I ran the URL, I still got the output: 
```
downloading url= /Economy/North-Korea-finds-a-new-friend-in-Russia ... WARNING: no html found for url= /Economy/North-Korea-finds-a-new-friend-in-Russia
downloading url= / ... WARNING: no html found for url= /
downloading url= / ... WARNING: no html found for url= /
downloading url= / ... WARNING: no html found for url= /
downloading url= / ... WARNING: no html found for url= /
```
Also, I am still having the issue where it isn't overwriting all of the articles when I run the command: 
```
$ cat urls/week1-raye | xargs python3 tests/test_golden.py --insert_urls
```
It outputs only this:
```
WARNING: url= http://autonewsproo.blogspot.com/2017/11/fact-us-military-considered-using_18.html already added; overwriting
WARNING: url= http://beijingcream.com/2012/12/pyongyang-racer-how-fast-can-you-speed-around-north-koreas-capital-city/ already added; overwriting
WARNING: url= http://blog.keia.org/2013/04/why-north-korea-isnt-interested-in-economic-reform/ already added; overwriting
WARNING: url= http://blogs.reuters.com/fullfocus/2011/10/06/hungry-in-north-korea/ already added; overwriting
```
Am I doing something wrong?

**Comment by mikeizbicki** [comment]
Your git pull didn't work, and you can see the reason why in these lines:
```
error: Your local changes to the following files would be overwritten by merge:
	metahtml/timestamp.py
	tests/.cache/invalid
	tests/golden.csv
Please commit your changes or stash them before you merge.
Aborting
```

**Comment by rayegleekel** [comment]
Thanks! Got it to work.
